#!/bin/bash

type zsh
if [ $? -ne 0 ]; then
  is_debian && aptitude -y install zsh
  is_osx    && brew install zsh
  is_centos && yum -y install zsh
fi

type go
if [ $? -ne 0 ]; then
  is_debian && aptitude -y install golang
  is_osx    && brew install go
  is_centos && yum -y install golang
fi

type vim
if [ $? -ne 0 ]; then
  is_debian && aptitude -y install vim
  is_osx    && brew install vim
  is_centos && yum -y install vim
fi

type git
if [ $? -ne 0 ]; then
  is_debian && aptitude -y install git
  is_osx    && brew install git
  is_centos && yum -y install git
fi

type zsh
if [ $? -ne 0 ]; then
  is_debian && aptitude -y install zsh
  is_osx    && brew install zsh
  is_centos && yum -y install zsh
fi
