#!/bin/bash

# include helper.sh
. helper.sh

# rbenv
git_clone_or_update https://github.com/sstephenson/rbenv.git ~/.rbenv

# ruby-build
git_clone_or_update https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# rbenv-binstubs
git_clone_or_update https://github.com/ianheggie/rbenv-binstubs.git ~/.rbenv/plugins/rbenv-binstubs
