#!/bin/bash

installers_dir=$(dirname $0)
scripts_dir=$(dirname $installers_dir)

# include helper.sh
. $scripts_dir/helpers/helper.sh

# oh-my-zsh
git_clone_or_update https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
